research_task:
  description: >
    Conduct a thorough market research about {name}
    Make sure you find the best deals and save the most amount of money.
  expected_output: >
    A list with 10 greatest deals of {name} found
    across the market with their price each. 
    This list should be ordered from the cheapest to the
    most expensive product.
  agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst
